# -*- coding: utf-8 -*-
"""movie recommender

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqb0x_JWsqjj_qxriiYA1UDDhxwKFmLH
"""

import pandas as pd, numpy as np

credit=pd.read_csv("tmdb_5000_credits.csv", engine='python')

movie=pd.read_csv("tmdb_5000_movies.csv", engine='python')

movie["movie_id"]=movie.id

movie.drop("id", axis=1, inplace=True)

data=movie.merge(credit, on='movie_id')

data.info()

input_col=data[['movie_id','genres','keywords','overview','tagline','title_x','crew','cast']]

df=pd.DataFrame(input_col)

df

df.cast[0]

import ast

df.cast=df.cast.apply(ast.literal_eval)
df.crew=df.crew.apply(ast.literal_eval)
df.genres=df.genres.apply(ast.literal_eval)
df.keywords=df.keywords.apply(ast.literal_eval)

def cast(list):
  cast_list=[]
  for i in list:
    cast_list.append(i['name'])
  return cast_list
# how did it get name value of every dict\.

def crew(list):
  crew_list=[]
  for i in list:
    if i['job']=='Director':
      crew_list.append(i['name'])
    if i['job']=='Producer':
      crew_list.append(i['name'])
  return crew_list

df['crew'] = df['crew'].apply(crew)

def genres(list):
  genres_list=[]
  for i in list:
    genres_list.append(i['name'])
  return genres_list

df['genres']=df['genres'].apply(genres)

def keywords(list):
  keywords_list=[]
  for i in list:
    keywords_list.append(i['name'])
  return keywords_list

df['cast'] = df['cast'].apply(cast)

df['keywords'] = df['keywords'].apply(keywords)

df.cast=df.cast.apply(lambda x:[i.replace(' ','') for i in x])

df.crew=df.crew.apply(lambda x:[i.replace(' ','') for i in x])

df['overview']=df.overview.apply(lambda x:str(x).split(' '))

df['tagline']=df.tagline.apply(lambda x:str(x).split(' '))

def split(list):
  new_list=[]
  for i in list:
    new_list.extend(i.split(' '))
  return new_list

df['keywords']=df.keywords.apply(split)

df["genres"]=df.genres.apply(lambda x:[i.replace(' ','') for i in x])

df.to_csv("movie_redefined",index=False)

df.head(4)

df['tags']=df.overview+df.tagline+df.genres+df.keywords+df.cast+df.crew

df.drop(columns=['overview','tagline','genres','keywords','cast','crew'], inplace=True)

df['tags']=df.tags.apply(lambda x:' '.join(x))

from nltk.stem.porter import PorterStemmer

ps=PorterStemmer()

def stem(text):
  list_of_words = []
  for i in text.split():
    list_of_words.append(ps.stem(i))
  return " ".join(list_of_words)

df.tags=df.tags.apply(stem)

df.tags

from sklearn.feature_extraction.text import CountVectorizer

counter=CountVectorizer(max_features=4000, stop_words='english')

vectors=counter.fit_transform(df.tags).toarray()

from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vectors)

indexed_list=[]
for i in similarity:
  movie=[]
  for index,j in enumerate(i):
    movie.append((index,float(j)))
  indexed_list.append(movie)

indexed_list[:5]

df.head(2)

df.to_csv("movie.csv",index=False)

print(df.title_x)

def recommend(movie):
  movie_index=df[df.title_x==movie].index[0]
  distances=indexed_list[movie_index]
  movies_list=sorted(distances,reverse=True,key=lambda x:x[1])[1:11]
  movies_names=[]
  for i in movies_list:
    movies_names.append(df.iloc[i[0]].title_x)
  return movies_names

